odin-kittens/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :kittens
  root "kittens#index"
end

odin-kittens/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

odin-kittens/app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, :cuteness, :softness, presence: true
end

odin-kittens/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

odin-kittens/app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.xml { render :xml => @kittens}
      format.json { render :json => @kittens}
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.xml { render :xml => @kitten}
      format.json { render :json => @kitten}
    end
  end

  def new
    @kitten = Kitten.build()
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to kitten_path(@kitten)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      redirect_to kitten_path(@kitten)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    redirect_to root_path
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

odin-kittens/app/helpers/application_helper.rb
module ApplicationHelper
end

odin-kittens/app/helpers/kittens_helper.rb
module KittensHelper
end

odin-kittens/app/views/kittens/_form.html.erb
<br>

<div>
    <%= form_with model: @kitten do |form| %>
        <%= form.label :name %>
        <%= form.text_field :name  %>

        <%= form.label :age %>
        <%= form.number_field :age, in: 0.0..35.0, step: 0.1 %>

        <%= form.label :cuteness %>
        <%= form.range_field :cuteness, in: 1..100 %>

        <%= form.label :softness %>
        <%= form.range_field :softness, in: 1..100 %>

        <br><br>
        <%= form.submit %>
    <% end %>
</div>

<br>
<%= link_to "[Home Page]", root_path %>

odin-kittens/app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

odin-kittens/app/views/kittens/delete.html.erb
<h1>Kittens#delete</h1>
<p>Find me in app/views/kittens/delete.html.erb</p>

odin-kittens/app/views/kittens/edit.html.erb
<% if @kitten.errors.any? %>
    <p>There are some errors in the form: </p>
    <ul>
        <% @kitten.errors.full_messages.each do |message| %>
            <li>
                <%= message %>
            </li>
        <% end %>
    </ul>
<% end %>


<h2>
    Edit your kitten !! What changed?
</h2>

<%= render "form", kitten: @kitten %>

odin-kittens/app/views/kittens/index.html.erb
<div>
    <h1>Kittens list !!</h1>
    <h3>Kittens, all the kittens...</h3>
</div>

<ul>
    <% @kittens.each do |kitten| %>
        <li>
            <p><strong>Name:</strong> <%= kitten.name %></p>
            <p><strong>Age (yr):</strong> <%= kitten.age %></p>
            <p><strong>Cuteness (%):</strong> <%= kitten.cuteness %></p>
            <p><strong>Softness (%):</strong> <%= kitten.softness %></p>
            <%= link_to "[Show]", kitten_path(kitten) %>
            <%= link_to "[Edit]", edit_kitten_path(kitten) %>
            <%= form_tag kitten_path(kitten), method: :delete do %>
                <%= button_to "[Delete Kitten]"  %>
            <% end %>
        </li>
    <% end %>
</ul>

<%= link_to "[Add New Kitten]", new_kitten_path %>

odin-kittens/app/views/kittens/new.html.erb
<% if @kitten.errors.any? %>
    <p>There are some errors in the form: </p>
    <ul>
        <% @kitten.errors.full_messages.each do |message| %>
            <li>
                <%= message %>
            </li>
        <% end %>
    </ul>
<% end %>

<h2>
    Add a Kitten, any Kitten !!
</h2>

<%= render "form", kitten: @kitten %>

odin-kittens/app/views/kittens/show.html.erb
<h2>This is the proud Kitten!: </h2>

<div>
    <p><strong>Name: </strong> <%= @kitten.name %></p>
    <p><strong>Age (in years): </strong> <%= @kitten.age %></p>
    <p><strong>Cuteness (from 0 to 100%): </strong> <%= @kitten.cuteness %></p>
    <p><strong>Softness (from 0 to 100%): </strong> <%= @kitten.softness %></p>
</div>

<h4>Quite the nice kitten, right ??</h4>

<p><%= link_to "[Edit Kitten]", edit_kitten_path(@kitten) %></p>

<p>See more.... <%= link_to "[Home Page]", root_path %></p>

odin-kittens/app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

odin-kittens/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>